### ISSUE TITLE
changed handler files for lambda from javascript to typescript but manifest is searching for the .js file in handler

### ISSUE THREAD

**Issue by Aabhusan** [DavidWells/serverless-manifest-plugin#17] opened 2020-11-27 05:46 UTC
I have separated my handler files and organised them in handler directory. Initially, i had written handler files in javascript but now i have changed my javascript code to typescript. Manifest plugin is still searching for the javascript code for generating config.
getProjects.js is converted into getProjects.ts 

This is message shown in the log:

` Creating Serverless manifest...

 
  Error --------------------------------------------------
 
  Error: File "handler/getProjects.js" not found. /home/aabhusan/Desktop/buildsort-proto/backend/services/buildsort-proto/handler/getProjects.js missing
      at getFunctionPath (/home/aabhusan/Desktop/buildsort-proto/backend/services/buildsort-proto/node_modules/serverless-manifest-plugin/src/index.js:520:11)
      at Object.keys.reduce (/home/aabhusan/Desktop/buildsort-proto/backend/services/buildsort-proto/node_modules/serverless-manifest-plugin/src/index.js:302:30)
      at Array.reduce (<anonymous>)
      at getFormattedData (/home/aabhusan/Desktop/buildsort-proto/backend/services/buildsort-proto/node_modules/serverless-manifest-plugin/src/index.js:198:52)
      at provider.request.then (/home/aabhusan/Desktop/buildsort-proto/backend/services/buildsort-proto/node_modules/serverless-manifest-plugin/src/index.js:74:30)
      at tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:15:14)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
      at process.topLevelDomainCallback (domain.js:126:23)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.`

**Comment by nhammond101** [comment] 2020-11-27 15:47
I ran in to this issue too, and my workaround was to change to the transpiled javascript output directory first and run the `sls manifest` command from there, 

eg `cd ./dist && sls -c ../serverless.yml  manifest --json`  

That command will create the manifest file in the file along side the serverless.yml using the js file(s) in the dist directory.  
Change the directory paths, etc to suit your local setup

**Comment by Aabhusan** [comment] 2020-11-30 06:23
thanks, @nhammond101 this works but it still throws an issue while executing the serverless.yml from the root directory

**Comment by nhammond101** [comment] 2020-11-30 07:12
What's the error? Can you add logs here?

**Comment by Aabhusan** [comment] 2020-11-30 07:41
While executing the serverless.yml file from the root directory with a serverless-manifest plugin, the manifest generating fails because manifest is looking for handlers in handler's directory but my handlers are in .webpack/services/handler 

![image](https://user-images.githubusercontent.com/37671561/100581290-9a3ac180-330f-11eb-92d8-0036d53a94fe.png)

**Comment by nhammond101** [comment] 2020-11-30 17:09
Yeah the issue is the working directory that the plugin starts in, it's using `process.cwd()`.  By defaulting to the project root, it can't find the transpiled JS.

The line of code is this [one](https://github.com/DavidWells/serverless-manifest-plugin/blob/f2c03f1391a92eeba530ab1a4d1df90dbf2ee91c/src/index.js#L307)

Ideally, the plugin could take an additional parameter specifying which directory to start in.  I'm assuming it's using the serverless config from the main serverless process which is specified via the `--configuration` parameter.

**Comment by DavidWells** [comment] 2020-11-30 17:32
Thanks for reporting this and troubleshooting. 

I'm open to having better Typescript support.

Maybe an optional config param `srcPath` passed into https://github.com/DavidWells/serverless-manifest-plugin/blob/f2c03f1391a92eeba530ab1a4d1df90dbf2ee91c/src/index.js#L74 will do the trick?

**Comment by DavidWells** [comment] 2020-12-01 17:34
Released with `serverless-manifest-plugin@1.0.7` as part of https://github.com/DavidWells/serverless-manifest-plugin/pull/18

**Comment by Aabhusan** [comment] 2020-12-02 11:02
srcPath can be used to pass handler's directory path other than default one.
example:

service: xxxxxxxxxxx

# Create an optimized package for our functions
package:
     individually: true

plugins:
     - serverless-offline
     - serverless-dotenv-plugin
     - serverless-manifest-plugin
     - serverless-webpack

custom:
     serverless-offline:
          port: 3000
     manifest:
          output: ../../../build-config/contracts-config.json
          srcPath: .webpack/service
     webpack:
          webpackConfig: './webpack.config.ts'
          includeModules: false

**Closed** 2020-12-02 11:03 UTC
